# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

#        bind:
#            App/Appointment/Infrastructure/Persistence/Repository/AppointmentRepositoryInterface: '@App\Appointment\Infrastructure\Persistence\Repository\AppointmentRepository'
#            App/Appointment/Infrastructure/Validation/AppointmentValidatorInterface: '@App\Appointment\Infrastructure\Validation\AppointmentValidator'

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

    command_handlers:
        namespace: App\Order\Application\Command\Handler\
        resource: '../src/Order/Application/Command/Handler/'
        autoconfigure: false
        tags:
            - { name: messenger.message_handler, bus: command.bus }

#    event_handlers:
#        namespace: App\Order\Application\DomainEventHandler\
#        resource: '../src/Order/Application/DomainEventHandler/'
#        autoconfigure: false
#        tags:
#            - { name: messenger.message_handler, bus: event.bus }

#    query_handlers:
#        namespace: App\Order\Application\Query\Handler\
#        resource: '../src/Order/Application/Query/Handler/'
#        autoconfigure: false
#        tags:
#            - { name: messenger.message_handler, bus: query.bus }
