name: Build

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - name: Build the PHP base docker image
      run: docker build . --file docker/php/Dockerfile.baseimage --tag lucianojr/order-service-php:$(git rev-parse HEAD)

    - uses: actions/checkout@master
    - name: Build the PHP dev docker image
      run: docker build . --file docker/php/Dockerfile.dev --tag lucianojr/order-service-php-dev:$(git rev-parse HEAD)

    - uses: actions/checkout@master
    - name: Build the PHP prod docker image
      run: docker build . --file docker/php/Dockerfile.prod --tag lucianojr/order-service-php-prod:$(git rev-parse HEAD)

    - uses: actions/checkout@master
    - name: Login docker hub
      run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login --username ${{ secrets.DOCKER_USERNAME }} --password-stdin

    - uses: actions/checkout@master
    - name: Push the base docker image to registry
      run: docker push lucianojr/order-service-php:$(git rev-parse HEAD)

    - uses: actions/checkout@v1
    - name: Validate composer.json and composer.lock
      run: composer validate -d app

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress --no-suggest -d app

    - name: Run phpstan
      run: composer run-script phpstan -d app

    - name: Run phpunit
      run: composer run-script phpunit -d app

    - uses: actions/checkout@v2
    - uses: shivammathur/setup-php@master
      with:
        coverage: pcov
        php-version: '7.4'
        extension: dom, fileinfo, mbstring
    - run: |
          composer install --no-suggest --prefer-dist --optimize-autoloader

    - uses: theomessin/action-phpcov
    - name: Run code coverage
      with:
        min_coverage: 0
        now_project: "action-phpcov"
        now_token: ${{ secrets.NOW_TOKEN }}
        phpunit: "composer run-script phpunit -d app"

    - name: Run phpstan
      run: composer run-script phpstan -d app
