name: Docker Image CI

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
      run: docker build . --file docker/php/Dockerfile.baseimage --tag lucianojr/order-service:$(git rev-parse HEAD)

    - uses: actions/checkout@v1
    - name: Login docker hub
      run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login --username ${{ secrets.DOCKER_USERNAME }} --password-stdin

    - uses: actions/checkout@v1
    - name: Push the Docker image to registry
      run: docker push lucianojr/order-service:$(git rev-parse HEAD)

