name: PHP project build

on: [push]

jobs:

  build:

    container: lucianojr/order-service-php-dev
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true

    steps:
      - uses: actions/checkout@master
      - name: Login docker hub
        run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login --username ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - uses: actions/checkout@master
      - name: Install composer dependecies
        run: composer install
