name: PHP Composer

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Validate composer.json and composer.lock
      run: composer validate -d app

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress --no-suggest -d app

    - name: Run tests
      run: bin/phpunit tests
